/**
 * @file Collision.hpp
 * @brief Defines structures used to represent collision results.
 */

#pragma once

#include "vec2.hpp"

namespace Garnet {

    /**
     * @brief Contains information describing a collision.
     *
     * Collision structures are generated by collision
     * detection algorithms and consumed by collision
     * resolution systems.
     *
     * The collision normal represents the direction of
     * separation while penetration represents the depth
     * of overlap between colliders.
     */
    struct Collision {

        /**
         * @brief Indicates whether a collision occurred.
         *
         * False when the tested colliders do not overlap.
         */
        bool hit = false;

        /**
         * @brief Collision surface normal.
         *
         * The normal points from the first collider
         * toward the second collider supplied to the
         * collision test.
         */
        vec2 normal{};

        /**
         * @brief Amount of overlap between colliders.
         *
         * This value is used by collision resolution
         * systems to separate intersecting entities.
         */
        float penetration = 0.0f;
    };

}