/**
 * @file Collision.hpp
 * @brief Provides collision detection and resolution systems.
 */

#pragma once

#include <cmath>

#include "Components.hpp"
#include "Components.hpp"
#include "Scene.hpp"
#include "vec2.hpp"

namespace Garnet {

/**
 * @brief Contains information describing a collision.
 *
 * Collision structures are generated by collision
 * detection algorithms and consumed by collision
 * resolution systems.
 *
 * The collision normal represents the direction of
 * separation while penetration represents the depth
 * of overlap between colliders.
 */
struct Collision {
	/**
	 * @brief Indicates whether a collision occurred.
	 *
	 * False when the tested colliders do not overlap.
	 */
	bool hit = false;

	/**
	 * @brief Collision surface normal.
	 *
	 * The normal points from the first collider
	 * toward the second collider supplied to the
	 * collision test.
	 */
	vec2 normal{};

	/**
	 * @brief Amount of overlap between colliders.
	 *
	 * This value is used by collision resolution
	 * systems to separate intersecting entities.
	 */
	float penetration = 0.0f;
};

/**
 * @brief Detects and resolves collider intersections.
 *
 * The CollisionSystem performs pairwise collision
 * checks on entities containing Transform and
 * Collider components. When a collision is detected,
 * overlapping entities are separated based upon
 * their Rigidbody properties.
 *
 * Currently only axis-aligned bounding box (AABB)
 * collisions are supported.
 */
class CollisionSystem {
	public:
	/**
	 * @brief Registers the collision system with a scene.
	 *
	 * Once initialized, collision processing will be
	 * executed automatically each time Scene::update()
	 * is called.
	 *
	 * @param scene Scene to bind to.
	 *
	 * @code
	 * CollisionSystem::Init(scene);
	 * @endcode
	 */
	static void Init(Scene& scene) { scene.bindSystem<Components::Transform, Components::Collider>(Update); }

	private:
	/**
	 * @brief Processes all collider interactions.
	 *
	 * Every collider pair in the registry is tested for
	 * intersection. When a collision occurs, entities
	 * with Rigidbody components are separated along
	 * the collision normal.
	 *
	 * @param dt Frame delta time.
	 * @param scene Scene being updated.
	 */
	static void Update(float dt, Registry& registry, const std::vector<Entity>& entities) {
		for (Entity a : entities){
			Components::Transform& transformA = registry.getComponent<Components::Transform>(a);
			Components::Collider& colliderA = registry.getComponent<Components::Collider>(a);
			for (Entity b: entities) {
				Components::Transform& transformB = registry.getComponent<Components::Transform>(b);
				Components::Collider& colliderB = registry.getComponent<Components::Collider>(b);

                if (a >= b) { return; }

				Collision collision =
					CheckAABB(transformA, colliderA, transformB, colliderB);

				if (!collision.hit) {
					return;
				}

				const bool aHasBody = registry.hasComponent<Components::Rigidbody>(a);

				const bool bHasBody = registry.hasComponent<Components::Rigidbody>(b);

				if (!aHasBody && !bHasBody) {
					return;
				}

				if (aHasBody && !bHasBody) {
					transformA.position =
						transformA.position - collision.normal * collision.penetration;

					return;
				}

				if (!aHasBody && bHasBody) {
					transformB.position =
						transformB.position + collision.normal * collision.penetration;

					return;
				}

				transformA.position =
					transformA.position - collision.normal * (collision.penetration * 0.5f);

				transformB.position =
					transformB.position + collision.normal * (collision.penetration * 0.5f);
			};
	    };
	}

	/**
	 * @brief Performs an axis-aligned bounding box
	 * collision test.
	 *
	 * Compares two AABB colliders and determines whether
	 * they overlap. If a collision occurs, information
	 * describing the overlap is returned for use by
	 * collision resolution systems.
	 *
	 * The collision normal points from the first collider
	 * toward the second collider.
	 *
	 * @param aTransform Transform associated with the first collider.
	 * @param a First collider.
	 * @param bTransform Transform associated with the second collider.
	 * @param b Second collider.
	 *
	 * @returns A Collision structure describing the collision.
	 */
	[[nodiscard]]
	static Collision CheckAABB(const Components::Transform& aTransform, const Components::Collider& a,
                               const Components::Transform& bTransform, const Components::Collider& b) {
        
		Collision result;

		const vec2 aHalf = a.size * 0.5f;
		const vec2 bHalf = b.size * 0.5f;
		const vec2 aCenter = aTransform.position + a.offset;
		const vec2 bCenter = bTransform.position + b.offset;

		const float dx = bCenter.x - aCenter.x;
		const float dy = bCenter.y - aCenter.y;
		const float overlapX = (aHalf.x + bHalf.x) - std::abs(dx);
		const float overlapY = (aHalf.y + bHalf.y) - std::abs(dy);

		if (overlapX <= 0.0f || overlapY <= 0.0f) { return result; }

		result.hit = true;

		if (overlapX < overlapY) {
			result.penetration = overlapX;
			result.normal = (dx > 0.0f) ? vec2{1.0f, 0.0f} : vec2{-1.0f, 0.0f};
		}
        else {
			result.penetration = overlapY;
			result.normal = (dy > 0.0f) ? vec2{0.0f, 1.0f} : vec2{0.0f, -1.0f};
		}

		return result;
	}
};

}  // namespace Garnet